/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thing.con;

import com.thing.con.config.SflProperties;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public void garbageTime() {
    }
}
