/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thing.con;

public class SlfLibrary {
    public boolean someLibraryMethod() {

        return true;
    }

    public void garbageTime() {
    }
}
