/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thing.con;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        SlfLibrary classUnderTest = new SlfLibrary();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
